ALTER TABLE [dbo].[Sys_Menus] ADD  CONSTRAINT [PK_SysMenus] PRIMARY KEY CLUSTERED 
(
	[M_MenuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
GO
