ALTER TABLE [dbo].[Sys_Department] ADD  CONSTRAINT [PK_SysDepartment] PRIMARY KEY CLUSTERED 
(
	[D_DeptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
GO
