CREATE TABLE [dbo].[Sys_AreaInfo]
(
	[A_Id] BIGINT NOT NULL IDENTITY(1,1), 
    [A_ParentId] BIGINT NOT NULL, 
    [A_Path] NVARCHAR(10) NOT NULL, 
    [A_Level] INT NOT NULL, 
    [A_CnName] NVARCHAR(50) NOT NULL, 
    [A_EnName] NVARCHAR(50) NOT NULL, 
    [A_PY] NVARCHAR(50) NOT NULL, 
    [A_Code] NVARCHAR(50) NOT NULL
)
